"""add spot api fields

Revision ID: 357bdb351b9c
Revises: 9bd6d8349d2d
Create Date: 2026-08-13 17:04:33.343003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357bdb351b9c'
down_revision: Union[str, Sequence[str], None] = '9bd6d8349d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('area_cd', sa.String(length=20), nullable=True))
    op.add_column('spots', sa.Column('signgu_cd', sa.String(length=20), nullable=True))
    op.add_column('spots', sa.Column('content_type_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_spots_area_cd'), 'spots', ['area_cd'], unique=False)
    op.create_index(op.f('ix_spots_signgu_cd'), 'spots', ['signgu_cd'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spots_signgu_cd'), table_name='spots')
    op.drop_index(op.f('ix_spots_area_cd'), table_name='spots')
    op.drop_column('spots', 'content_type_id')
    op.drop_column('spots', 'signgu_cd')
    op.drop_column('spots', 'area_cd')
    # ### end Alembic commands ###
