"""create shared courses table

Revision ID: 5f2e6c1600a8
Revises: e1cbc7345fdf
Create Date: 2026-08-13 18:43:18.746841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2e6c1600a8'
down_revision: Union[str, Sequence[str], None] = 'e1cbc7345fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_courses',
    sa.Column('share_id', sa.String(length=32), nullable=False),
    sa.Column('spot_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('share_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_courses')
    # ### end Alembic commands ###
