"""create spots table

Revision ID: 9bd6d8349d2d
Revises: 
Create Date: 2026-08-13 16:50:26.490001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd6d8349d2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_spot_name', sa.String(length=255), nullable=False),
    sa.Column('sido', sa.String(length=100), nullable=True),
    sa.Column('sigungu', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('category_large', sa.String(length=100), nullable=True),
    sa.Column('category_medium', sa.String(length=100), nullable=True),
    sa.Column('category_small', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('mapx', sa.Float(), nullable=True),
    sa.Column('mapy', sa.Float(), nullable=True),
    sa.Column('cnctr_rate_7d_avg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spots_id'), 'spots', ['id'], unique=False)
    op.create_index(op.f('ix_spots_sido'), 'spots', ['sido'], unique=False)
    op.create_index(op.f('ix_spots_sigungu'), 'spots', ['sigungu'], unique=False)
    op.create_index(op.f('ix_spots_tourist_spot_name'), 'spots', ['tourist_spot_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spots_tourist_spot_name'), table_name='spots')
    op.drop_index(op.f('ix_spots_sigungu'), table_name='spots')
    op.drop_index(op.f('ix_spots_sido'), table_name='spots')
    op.drop_index(op.f('ix_spots_id'), table_name='spots')
    op.drop_table('spots')
    # ### end Alembic commands ###
