"""restore spot content type id

Revision ID: e1cbc7345fdf
Revises: 7da4a2e43539
Create Date: 2026-08-13 17:24:45.007930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1cbc7345fdf'
down_revision: Union[str, Sequence[str], None] = '7da4a2e43539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('content_type_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'content_type_id')
    # ### end Alembic commands ###
