"""add spot content id

Revision ID: 7da4a2e43539
Revises: 357bdb351b9c
Create Date: 2026-08-13 17:23:25.019234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da4a2e43539'
down_revision: Union[str, Sequence[str], None] = '357bdb351b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('content_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_spots_content_id'), 'spots', ['content_id'], unique=True)
    op.drop_column('spots', 'content_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('content_type_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_spots_content_id'), table_name='spots')
    op.drop_column('spots', 'content_id')
    # ### end Alembic commands ###
